# Generated by Django 3.0.7 on 2020-06-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
