# Generated by Django 3.0.7 on 2020-07-05 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0002_auto_20200705_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='size',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
