# Generated by Django 3.0.7 on 2020-06-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0003_auto_20200608_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='discipline',
            field=models.CharField(default="PlayerUnknown'sBattleGround", max_length=100),
            preserve_default=False,
        ),
    ]
