# Generated by Django 3.0.7 on 2020-07-28 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0003_auto_20200728_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='esports.Tournament'),
        ),
    ]
