# Generated by Django 3.0.7 on 2020-07-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0005_auto_20200705_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
