# Generated by Django 3.0.7 on 2020-06-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('esports', '0005_auto_20200612_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='is_team',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
