# Generated by Django 3.0.7 on 2020-07-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0005_auto_20200728_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='joined',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
