# Generated by Django 3.0.7 on 2020-07-29 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0006_tournament_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='joined',
        ),
    ]
