# Generated by Django 3.0.7 on 2020-06-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('esports', '0006_auto_20200615_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='is_team',
            field=models.BooleanField(default=False),
        ),
    ]
