# Generated by Django 3.0.7 on 2020-07-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0006_auto_20200706_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
