# Generated by Django 3.0.7 on 2020-07-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0007_auto_20200706_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
