# Generated by Django 3.0.7 on 2020-06-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0007_auto_20200615_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
