# Generated by Django 3.0.7 on 2020-07-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0010_remove_participant_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
