# Generated by Django 3.0.7 on 2020-07-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0012_auto_20200707_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team_name',
        ),
    ]
